### ISSUE TITLE
Exceeding execution time limit

### ISSUE THREAD

**Issue by ebebbington** [maman/deno-playground#15]
When running the following:

```
import { Drash } from "https://deno.land/x/drash@v1.3.0/mod.ts";
```

After about 5ish seconds, i get:

```
Exceeding execution time limit
```

Any possibility of increasing the timeout or configure it in the UI?

**Comment by maman** [comment]
Hi, sorry for the late reply!

It's configurable here: https://github.com/maman/deno-playground/blob/master/lib/createCommandHandler.ts#L51, so you can definitely increase the timeout if you self-hosting the playground, in the environment that you control.

The reason that I'm not exposing the timeout configuration from the UI is to have some control about the process that someone run on the playground - since it's accessible by anyone on the internet, it'll be bad if someone decides to stresstest/overwhelm the servers by running expensive/long running code on the playground.
