### ISSUE TITLE
Environment variables are exposed to public

### ISSUE THREAD

**Issue by searchableguy** [maman/deno-playground#16]
### Reproduction code

```ts
console.log(JSON.stringify(Deno.env.toObject()));
```

This will expose all the environment variables. Some of which are sensitive and prone to abuse. 

I tried to contact you in private but I couldn't find your contact information.

**Comment by maman** [comment]
Holyshit

yep that's true, and I didn't think thoroughly before - and it seems that there are some vercel-specific AWS credentials on the envvars.

this is due to the [now-deno](https://github.com/lucacasonato/now-deno) runtime that this project uses: https://github.com/lucacasonato/now-deno/blob/master/src/index.ts#L26

which in turn uses deno-lambda, which specifies `-A` flags to deno: https://github.com/hayd/deno-lambda/blob/2c5ef7062a04078996387fae62772331bf6cf665/runtime/bootstrap#L22

I'm not sure how to fixes this - I think it's better to contact vercel first, lemme do that.

Thanks for the findings!

**Comment by maman** [comment]
Also I merged a temporary fixes, very basic and naive solutions to deno playground which disables `Deno.env` execution

**Comment by maman** [comment]
I'll lock the conversation for now, while waiting vercel support to reply
